# app/ml_engine/ml_base_engine.py
from abc import ABC, abstractmethod

class BaseMLEngine(ABC):
    """
    Abstract Base Class acting as the explicit structural contract 
    for all core Machine Learning and Context Tokenizer services.
    """

    @abstractmethod
    def tokenize_text(self, input_text: str) -> list:
        """
        Transforms a raw input string into an index array of mathematical tokens.

        Args:
            input_text (str): The raw text or vocal transcription string.

        Returns:
            list: An array of calculated integer token IDs matching the model vocabulary.
        """
        pass  # pragma: no cover

    @abstractmethod
    def generate_response(self, user_text: str, tracking_context: str) -> str:
        """
        Executes model inference to yield a natural language response bounding
        user intent with environment status strings.

        Args:
            user_text (str): The transcribed vocal or textual query from the user.
            tracking_context (str): The active state payload of items seen by the camera.

        Returns:
            str: A processed conversational answer generated by the ML model.
        """
        pass  # pragma: no cover

    @abstractmethod
    def generate_general_response(self, user_text: str) -> str:
        """
        Handles general knowledge queries outside the lost-item domain.

        Args:
            user_text (str): The transcribed vocal or textual query from the user.

        Returns:
            str: A concise conversational answer suitable for voice playback.
        """
        pass  # pragma: no cover